"""create switch table

Revision ID: 11c3b44d3cf7
Revises: 
Create Date: 2023-05-06 21:52:46.711331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c3b44d3cf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyboard_type')
    op.drop_table('keyboard')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyboard',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('keyboard_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('switch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('keycap_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['keyboard_type_id'], ['keyboard_type.id'], name='keyboard_keyboard_type_id_fkey'),
    sa.ForeignKeyConstraint(['keycap_id'], ['keycap.id'], name='keyboard_keycap_id_fkey'),
    sa.ForeignKeyConstraint(['switch_id'], ['switch.id'], name='keyboard_switch_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='keyboard_pkey')
    )
    op.create_table('keyboard_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('keyboard_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='keyboard_type_pkey')
    )
    # ### end Alembic commands ###
